# Generated by Django 3.2 on 2021-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název firmy', max_length=50, unique=True, verbose_name='Název firmy')),
                ('sidlo', models.CharField(help_text='Zadejte sídlo firmy', max_length=50, verbose_name='Sídlo')),
                ('pocet_zamestnancu', models.IntegerField(blank=True, help_text='Zadejte počet zaměstnanců')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název hry', max_length=50, verbose_name='Název hry')),
                ('jazyk', models.CharField(choices=[('Angličtina', 'Angličtina'), ('Čeština', 'Čeština')], default='Angličtina', max_length=10)),
                ('zanr', models.CharField(help_text='Zadejte žánr hry', max_length=50, verbose_name='Žánr')),
                ('rating', models.CharField(choices=[('E', 'E'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], default='E', max_length=2)),
                ('plakat', models.ImageField(blank=True, null=True, upload_to='hra/plakat/%Y/%m/%d/', verbose_name='plakat')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('vydavatel', models.ManyToManyField(help_text='Vyberte vydavatele hry', to='games.Firma')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název platformy', max_length=50, unique=True, verbose_name='Název platformy')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vydani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(help_text='Zadejte datum vydání hry', verbose_name='Release date')),
                ('hra', models.ManyToManyField(help_text='Vyberte hru která vychází tento den', to='games.Hra')),
                ('platforma', models.ManyToManyField(help_text='Vyberte platformu na kterou vychází hra', to='games.Platforma')),
            ],
            options={
                'ordering': ['datum'],
            },
        ),
    ]
