# Generated by Django 3.2 on 2021-06-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210614_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='platforma',
            field=models.ManyToManyField(help_text='Vyberte platformu', to='games.Platforma'),
        ),
    ]
