# Generated by Django 3.2 on 2021-05-12 18:43

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210418_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenze',
            options={'ordering': ['prezdivka']},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Poster', 'Poster'), ('video', 'Video'), ('other', 'Other')], default='Poster', help_text='Select allowed attachment type', max_length=7, verbose_name='Attachment type')),
                ('hra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hra')),
            ],
        ),
    ]
