# Generated by Django 3.2 on 2021-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210512_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='rating',
            field=models.CharField(choices=[('E', 'EE'), ('7', 'SE'), ('12', 'TW'), ('15', 'FI'), ('18', 'EI')], default='E', max_length=2),
        ),
    ]
