# Generated by Django 3.2 on 2021-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_hra_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='rating',
            field=models.CharField(choices=[('E', 'E'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], default='E', max_length=2),
        ),
    ]
