# Generated by Django 3.2 on 2021-05-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_hra_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
