# Generated by Django 3.2 on 2021-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_delete_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='hra/plakat/%Y/%m/%d/', verbose_name='plakat'),
        ),
    ]
